---

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: operatehappy/packer-github-action
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-action
        with:
          command: validate
          arguments: -syntax-only
          target: packer/veeam.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-action
        with:
          command: build
          arguments: "-color=false -on-error=abort"

...
